import { jsPDF } from 'jspdf';
import type { CalculatorInputs, CalculatorResults } from '../store/types';
import { formatCurrency, formatPercent } from './format';

export async function exportPDF(
  inputs: CalculatorInputs,
  results: CalculatorResults,
): Promise<void> {
  const doc = new jsPDF();
  const now = new Date();
  const dateStr = now.toISOString().split('T')[0];

  // Helper to add text at position with automatic line tracking
  let y = 20;
  const addLine = (text: string, fontSize = 10, bold = false) => {
    doc.setFontSize(fontSize);
    if (bold) doc.setFont('helvetica', 'bold');
    else doc.setFont('helvetica', 'normal');
    doc.text(text, 15, y);
    y += fontSize * 0.5 + 2;
  };
  const addRow = (label: string, value: string) => {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(label, 20, y);
    doc.text(value, 120, y);
    y += 7;
  };

  // Page 1: Summary
  addLine('Mortgage Calculator Report', 18, true);
  addLine(`Generated: ${now.toLocaleDateString()}`, 10);
  y += 5;

  addLine('Inputs', 14, true);
  addRow('Home Price:', formatCurrency(inputs.purchasePrice));
  addRow('Down Payment:', `${inputs.downPaymentPercent}%`);
  addRow('Interest Rate:', formatPercent(inputs.interestRate));
  addRow('Loan Term:', `${inputs.loanTerm} years`);
  addRow('State:', inputs.selectedState);
  addRow('Property Tax Rate:', formatPercent(inputs.propertyTaxRate));
  y += 5;

  addLine('Monthly Payment Breakdown', 14, true);
  addRow('Principal & Interest:', formatCurrency(results.piti.monthlyPI));
  addRow('Property Tax:', formatCurrency(results.piti.monthlyPropertyTax));
  addRow('Insurance:', formatCurrency(results.piti.monthlyInsurance));
  if (results.piti.monthlyHOA > 0)
    addRow('HOA:', formatCurrency(results.piti.monthlyHOA));
  if (results.piti.monthlyPMI > 0)
    addRow('PMI:', formatCurrency(results.piti.monthlyPMI));
  addRow('Maintenance:', formatCurrency(results.piti.monthlyMaintenance));
  addRow('Utilities:', formatCurrency(results.piti.monthlyUtilities));
  addRow('PITI Total:', formatCurrency(results.piti.monthlyPITI));
  addRow('True Monthly Cost:', formatCurrency(results.piti.trueMonthlyCost));
  y += 5;

  addLine('Upfront Costs', 14, true);
  addRow('Down Payment:', formatCurrency(results.piti.downPayment));
  addRow(
    'Closing Costs:',
    formatCurrency(results.upfrontCosts.totalClosingCosts),
  );
  addRow(
    'Total Cash Needed:',
    formatCurrency(results.upfrontCosts.totalCashNeeded),
  );

  // Footer
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.text(
    'Generated by Mortgage Calculator v2 | Not financial advice',
    15,
    285,
  );

  // Page 2
  doc.addPage();
  y = 20;

  addLine('Tax Benefits', 14, true);
  addRow(
    'Annual Tax Benefit:',
    formatCurrency(results.taxBenefits.totalAnnualTaxBenefit),
  );
  addRow(
    'Federal Savings:',
    formatCurrency(results.taxBenefits.federalTaxSavings),
  );
  addRow(
    'State Savings:',
    formatCurrency(results.taxBenefits.stateTaxSavings),
  );
  addRow(
    'Monthly Benefit:',
    formatCurrency(results.taxBenefits.monthlyTaxSavings),
  );
  y += 5;

  addLine('Affordability', 14, true);
  addRow(
    'Max Purchase Price:',
    formatCurrency(results.affordability.maxPurchasePrice),
  );
  addRow(
    'Target Monthly PITI (28% DTI):',
    formatCurrency(results.affordability.targetPITI),
  );
  y += 5;

  addLine('Extra Payments', 14, true);
  addRow(
    'Interest Saved:',
    formatCurrency(results.extraPayments.interestSaved),
  );
  addRow('Months Saved:', String(results.extraPayments.monthsSaved));
  y += 5;

  if (results.pmiTimeline.hasPMI) {
    addLine('PMI Analysis', 14, true);
    addRow('Monthly PMI:', formatCurrency(results.pmiTimeline.monthlyPMI));
    addRow(
      'Auto-Removal:',
      `Month ${results.pmiTimeline.autoRemovalMonth ?? 'N/A'}`,
    );
    addRow(
      'Total PMI Cost:',
      formatCurrency(results.pmiTimeline.totalPMIPaidUntilAuto),
    );
    y += 5;
  }

  const lastYear = results.amortization[results.amortization.length - 1];
  if (lastYear) {
    addLine('10-Year Wealth Projection', 14, true);
    addRow('Home Value:', formatCurrency(lastYear.homeValue));
    addRow('Total Equity:', formatCurrency(lastYear.totalEquity));
    addRow('Total Wealth Impact:', formatCurrency(lastYear.totalWealthImpact));
  }

  // Footer
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.text(
    'Generated by Mortgage Calculator v2 | Not financial advice',
    15,
    285,
  );

  doc.save(`mortgage-calculator-${dateStr}.pdf`);
}
